version: '3.3'
services: 
    downloader:
        container_name: yt_dl
        build: 
            dockerfile: Dockerfile
            context: .
        entrypoint: ["tail", "-f", "/dev/null"]
        volumes: 
            - ./python:/application